### ISSUE TITLE
Does claircli supports the most up-to-date version of clair?

### ISSUE THREAD

**Issue by hrist0stoichev** [joelee2012/claircli#10]
I have the most up-to-date version of `clair` running in a Docker container and I try to scan an arbitrary image from Docker Hub using `claircli` but without success.

I run `claircli python:3.4-alpine` and from the logs I can see that the 5 layers of the image are detected correctly. `Claircli` then makes 2 requests to `clair` (from `clair` logs):
1. DELETE to `/v1/layers/sha256:8e402f1a9c577ded051c1ef10e9fe4492890459522089959988a4852dee8ab2c`
2. POST to `/v1/layers`

Both requests return 404 and I think the reason for this is that those endpoints do not exist. Looking at [clair.proto](https://github.com/quay/clair/blob/master/api/v3/clairpb/clair.proto), I don't see such endpoints.

The claircli logs then output
```
|WARNING|<Image: python:3.4-alpine> was not found
|INFO|============================================================
|INFO|            CLAIR ANALYSIS REPORTS: (1) IN TOTAL
|INFO|============================================================
|ERROR|IMAGES COULD NOT BE FOUND (1)
|ERROR|python:3.4-alpine
```

Looking at `claircli` source code, it looks like that all 404 status codes are treated like that but the actual reason for the 404 is that the endpoint does not exist.

Am I doing anything wrong or just `claircli` does not support newer version of `clair`?

**Comment by hrist0stoichev** [comment]
It looks like only Clair API v1 is supported and I tried running Claircli agains the v3 API.

**Comment by joelee2012** [comment]
Yes， only api v1 is supported due to [clair](https://github.com/quay/clair/releases) does not release 3.x which includes new api
