### ISSUE TITLE
Does the cli support scanning images in AWS ECR?

### ISSUE THREAD

**Issue by ssunkari** [joelee2012/claircli#9]

**Comment by joelee2012** [comment]
No, claircli retrieves [Docker Registry v2 Bearer token](https://docs.docker.com/registry/spec/auth/jwt/) to get manifest and layer info which is not supported by AWS ECR.
A possible solution is passing  [HTTP API Authentication token](https://docs.aws.amazon.com/AmazonECR/latest/userguide/registries.html#registry_auth_http) comes from AWS CLI to claircli. eg, a file parameter include content like: 
`{'012345678910.dkr.ecr.us-east-1.amazonaws.com': {'': 'token', 'repo1': 'token'}}`
then merge this json into `claircli:RemoteRegistry.tokens`

Feel free to open pull request for new feature

**Comment by groboclown** [comment]
I created a PR to address this issue ( #16 ).
